apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ejercicio-5.fullname" . }}
  labels:
    {{- include "ejercicio-5.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ejercicio-5.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ejercicio-5.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "80"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
