apiVersion: v1
kind: Service
metadata:
  name: {{ include "ejercicio-5.fullname" . }}
  labels:
    {{- include "ejercicio-5.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "ejercicio-5.selectorLabels" . | nindent 4 }}
